name: Run Scraper

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  run-scraper-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Chrome and Chromedriver
        run: |
          sudo apt update
          sudo apt install -y wget unzip curl gnupg libglib2.0-0 libnss3 libxss1 \
            libatk-bridge2.0-0 libgtk-3-0 libu2f-udev libvulkan1 libxi6 libxtst6 \
            fonts-liberation xdg-utils
          wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/124.0.6367.91/linux64/chrome-linux64.zip
          unzip chrome-linux64.zip
          sudo mv chrome-linux64 /opt/google
          sudo ln -sf /opt/google/chrome-linux64/chrome /usr/bin/google-chrome
          wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/124.0.6367.91/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  # Now in root directory

      - name: Run Scraper
        run: python scraper/scraper.py

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: scraped-data
          path: |
            allcorectpricees.csv
            allcorectpricees.zip
